spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/OrderSystem
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    visibility:
      field: any
      getter: none
      is-getter: none

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect